ADMINISTRATOR = "Administrator"
VETERINARY_STAFF = "Veterinary Staff"
FIELD_PERSONNEL = "Field Personnel"

ADMIN_DASHBOARD_ROLES = (ADMINISTRATOR, VETERINARY_STAFF)
ALL_AUTHENTICATED_ROLES = (ADMINISTRATOR, VETERINARY_STAFF, FIELD_PERSONNEL)
