export const ROLES = {
  ADMINISTRATOR: "Administrator",
  VETERINARY_STAFF: "Veterinary Staff",
  FIELD_PERSONNEL: "Field Personnel",
};

export const ADMIN_DASHBOARD_ROLES = [ROLES.ADMINISTRATOR, ROLES.VETERINARY_STAFF];
export const ADMIN_ONLY_ROLES = [ROLES.ADMINISTRATOR];
